language: node_js
node_js:
  - "8.4.0"
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
before_deploy:
  - sed -i '/dist/d' .gitignore
  - sed -i '/index.html/d' .gitignore
